logging:
  level:
    root: DEBUG
  path: ../log
server:
  port: 8765
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password:  admin1234
    url: jdbc:mysql://127.0.0.1:3306/rebot?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 'x'
      test-while-idle: true
      time-between-eviction-runs-millis: 300000
      num-tests-per-eviction-run: 50
      soft-min-evictable-idle-time-millis: 3600000
#让mybatis知道mapper在哪里
mybatis:
    mapper-locations: classpath:mapper/*.xml
#分页的配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
  
rebot:
  dhcp-client-cmd: d:\seadun\bin\dhcp_startup.bat
