-- MySQL Script generated by MySQL Workbench
-- Fri Mar 16 16:26:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rebot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rebot` ;

-- -----------------------------------------------------
-- Schema rebot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rebot` DEFAULT CHARACTER SET utf8 ;
USE `rebot` ;

-- -----------------------------------------------------
-- Table `rebot`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rebot`.`user` ;

CREATE TABLE IF NOT EXISTS `rebot`.`user` (
  `id` INT NOT NULL COMMENT '物理组件',
  `user_name` VARCHAR(45) NOT NULL COMMENT '用户名 不可为空 唯一',
  `user_password` VARCHAR(45) NOT NULL COMMENT '密码 不可为空',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
