-- MySQL Script generated by MySQL Workbench
-- Wed Jul 11 21:56:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rebot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rebot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rebot` DEFAULT CHARACTER SET utf8 ;
USE `rebot` ;

-- -----------------------------------------------------
-- Table `rebot`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebot`.`user` (
  `id` VARCHAR(45) NOT NULL COMMENT '物理组件',
  `user_name` VARCHAR(45) NOT NULL COMMENT '用户名 不可为空 唯一',
  `user_password` VARCHAR(45) NOT NULL COMMENT '密码 不可为空',
  `crt_time` DATETIME NULL,
  `crt_user` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB
COMMENT = '用户表，默认用户admin密码cacjszx@123';


-- -----------------------------------------------------
-- Table `rebot`.`computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebot`.`computer` (
  `id` VARCHAR(45) NOT NULL COMMENT '由密查工具提供UUID',
  `bios_sn` VARCHAR(45) NULL COMMENT '设备序列号',
  `op_system` VARCHAR(45) NULL COMMENT '操作系统',
  `op_install_date` VARCHAR(45) NULL COMMENT '操作系统安装时间',
  `ip` VARCHAR(45) NULL COMMENT '客户端IP',
  `crt_date` DATETIME NULL,
  `upt_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '计算机的主要信息';


-- -----------------------------------------------------
-- Table `rebot`.`disk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebot`.`disk` (
  `id` VARCHAR(45) NOT NULL,
  `computer_id` VARCHAR(45) NULL COMMENT '由密查工具提供UUID',
  `disk_sn` VARCHAR(45) NULL COMMENT '硬盘序列号',
  `disk_interface_type` VARCHAR(45) NULL COMMENT '硬盘接口类型',
  `disk_capacity` VARCHAR(45) NULL COMMENT '硬盘容量',
  `disk_shell_sn` VARCHAR(45) NULL COMMENT '硬盘外壳号',
  `crt_time` DATETIME NULL,
  `upt_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bz_unique` (`computer_id` ASC, `disk_sn` ASC))
ENGINE = InnoDB
COMMENT = '磁盘';


-- -----------------------------------------------------
-- Table `rebot`.`network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebot`.`network` (
  `id` VARCHAR(45) NOT NULL,
  `computer_id` VARCHAR(45) NULL COMMENT '由密查工具提供UUID',
  `mac_address` VARCHAR(45) NULL COMMENT 'MACAddress',
  `crt_time` DATETIME NULL,
  `upt_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bz_unique` (`computer_id` ASC, `mac_address` ASC))
ENGINE = InnoDB
COMMENT = '网卡信息';


-- -----------------------------------------------------
-- Table `rebot`.`memory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebot`.`memory` (
  `id` VARCHAR(45) NOT NULL,
  `computer_id` VARCHAR(45) NULL COMMENT '由密查工具提供UUID',
  `mem_sn` VARCHAR(45) NULL COMMENT '内存序列号',
  `mem_type` VARCHAR(45) NULL COMMENT '内存类型',
  `mem_capacity` VARCHAR(45) NULL COMMENT '内存容量',
  `crt_time` DATETIME NULL,
  `upt_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bz_unique` (`computer_id` ASC, `mem_sn` ASC))
ENGINE = InnoDB
COMMENT = '内存';


-- -----------------------------------------------------
-- Table `rebot`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebot`.`video` (
  `id` VARCHAR(45) NOT NULL,
  `computer_id` VARCHAR(45) NULL,
  `video_sn` VARCHAR(45) NULL COMMENT '显卡序列号',
  `video_type` VARCHAR(45) NULL COMMENT '显卡型号',
  `crt_time` DATETIME NULL,
  `upt_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `video_UNIQUE` (`computer_id` ASC, `video_sn` ASC))
ENGINE = InnoDB
COMMENT = '显卡信息';


-- -----------------------------------------------------
-- Table `rebot`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebot`.`contract` (
  `id` VARCHAR(45) NOT NULL,
  `contract` VARCHAR(45) NULL COMMENT '合同编号',
  `crt_time` DATETIME NULL,
  `upt_time` DATETIME NULL,
  `status` VARCHAR(45) NOT NULL COMMENT 'YES --待验机\nNO --无须验机',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `contract_id_UNIQUE` (`contract` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rebot`.`contract_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebot`.`contract_detail` (
  `id` VARCHAR(45) NOT NULL,
  `contract_id` VARCHAR(45) NULL COMMENT '合同编号',
  `eq_type` VARCHAR(45) NULL COMMENT '合同名称',
  `eq_no` VARCHAR(45) NULL COMMENT 'NO未分配\nYES已分配',
  `computer_id` VARCHAR(45) NULL COMMENT '由密查工具提供UUID',
  `crt_time` DATETIME NULL COMMENT '分配时间',
  `upt_time` DATETIME NULL COMMENT '更新时间、验机确认时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eq_no_UNIQUE` (`eq_no` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
