package com.conan.crawler.server.pre.entity;

import java.util.Date;

public class GoodsTb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tb.id
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tb.shop_id
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tb.goods_id
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tb.crt_user
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    private String crtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tb.crt_time
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tb.status
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tb.crt_ip
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    private String crtIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tb.id
     *
     * @return the value of goods_tb.id
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tb.id
     *
     * @param id the value for goods_tb.id
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tb.shop_id
     *
     * @return the value of goods_tb.shop_id
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tb.shop_id
     *
     * @param shopId the value for goods_tb.shop_id
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tb.goods_id
     *
     * @return the value of goods_tb.goods_id
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tb.goods_id
     *
     * @param goodsId the value for goods_tb.goods_id
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tb.crt_user
     *
     * @return the value of goods_tb.crt_user
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tb.crt_user
     *
     * @param crtUser the value for goods_tb.crt_user
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tb.crt_time
     *
     * @return the value of goods_tb.crt_time
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tb.crt_time
     *
     * @param crtTime the value for goods_tb.crt_time
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tb.status
     *
     * @return the value of goods_tb.status
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tb.status
     *
     * @param status the value for goods_tb.status
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tb.crt_ip
     *
     * @return the value of goods_tb.crt_ip
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public String getCrtIp() {
        return crtIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tb.crt_ip
     *
     * @param crtIp the value for goods_tb.crt_ip
     *
     * @mbg.generated Sun Apr 01 12:17:12 CST 2018
     */
    public void setCrtIp(String crtIp) {
        this.crtIp = crtIp == null ? null : crtIp.trim();
    }
}