package com.conan.crawler.server.pre.entity;

import java.util.Date;

public class ShopTb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tb.id
     *
     * @mbg.generated Thu Apr 05 11:16:36 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tb.shop_name
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tb.shop_id
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tb.crt_user
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    private String crtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tb.crt_time
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tb.crt_ip
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    private String crtIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tb.status
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tb.shop_type
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    private String shopType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tb.id
     *
     * @return the value of shop_tb.id
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tb.id
     *
     * @param id the value for shop_tb.id
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tb.shop_name
     *
     * @return the value of shop_tb.shop_name
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tb.shop_name
     *
     * @param shopName the value for shop_tb.shop_name
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tb.shop_id
     *
     * @return the value of shop_tb.shop_id
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tb.shop_id
     *
     * @param shopId the value for shop_tb.shop_id
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tb.crt_user
     *
     * @return the value of shop_tb.crt_user
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tb.crt_user
     *
     * @param crtUser the value for shop_tb.crt_user
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tb.crt_time
     *
     * @return the value of shop_tb.crt_time
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tb.crt_time
     *
     * @param crtTime the value for shop_tb.crt_time
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tb.crt_ip
     *
     * @return the value of shop_tb.crt_ip
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public String getCrtIp() {
        return crtIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tb.crt_ip
     *
     * @param crtIp the value for shop_tb.crt_ip
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public void setCrtIp(String crtIp) {
        this.crtIp = crtIp == null ? null : crtIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tb.status
     *
     * @return the value of shop_tb.status
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tb.status
     *
     * @param status the value for shop_tb.status
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tb.shop_type
     *
     * @return the value of shop_tb.shop_type
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public String getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tb.shop_type
     *
     * @param shopType the value for shop_tb.shop_type
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    public void setShopType(String shopType) {
        this.shopType = shopType == null ? null : shopType.trim();
    }
}