package com.conan.crawler.server.pre.mapper;

import java.util.List;

import com.conan.crawler.server.pre.entity.ShopTb;

public interface ShopTbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    int insert(ShopTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    int insertSelective(ShopTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    ShopTb selectByPrimaryKey(String id);
    
    List<ShopTb> selectByShopType(String shopType);
    
    List<ShopTb> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    int updateByPrimaryKeySelective(ShopTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:16:37 CST 2018
     */
    int updateByPrimaryKey(ShopTb record);
}